language: objective-c
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=builds.appcelerator.com"
   - "MODULE_NAME=ti.map"
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl -o install.sh https://raw.githubusercontent.com/ashcoding/ci/timapFix/travis/install.sh #change this to appcelerator-modules once PR has been merged
    - source install.sh -s "--branch 4_1_X"
script: 
    - curl -o script.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/script.sh
    - source script.sh
after_success: # and this only on success
  - curl -o deploy.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/deploy.sh
  - source deploy.sh
